# Generated by Django 3.1.7 on 2021-03-13 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=250)),
                ('title_pt', models.CharField(max_length=250)),
                ('author', models.CharField(max_length=250, null=True)),
                ('description', models.CharField(max_length=500, null=True)),
                ('slug', models.CharField(max_length=250, null=True)),
                ('aff_link', models.CharField(max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Influencer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=500, null=True)),
                ('slug', models.CharField(max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recommended_books', models.ManyToManyField(related_name='influencer_who_recommends', to='main.Book')),
                ('written_books', models.ManyToManyField(related_name='influencer_who_wrote', to='main.Book')),
            ],
        ),
    ]
