# Generated by Django 3.1.7 on 2021-03-13 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210313_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='influencer',
            name='recommended_books',
            field=models.ManyToManyField(blank=True, null=True, related_name='influencer_who_recommends', to='main.Book'),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='written_books',
            field=models.ManyToManyField(blank=True, null=True, related_name='influencer_who_wrote', to='main.Book'),
        ),
    ]
