# Generated by Django 3.1.7 on 2021-03-14 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210313_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencer',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
