# Generated by Django 3.1.7 on 2021-03-14 01:25

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_influencer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='influencer',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=0, size=[300, 300], upload_to=''),
        ),
    ]
