# Generated by Django 3.1.7 on 2021-03-14 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210314_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title_pt',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='recommended_books',
            field=models.ManyToManyField(blank=True, related_name='influencer_who_recommends', to='main.Book'),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='written_books',
            field=models.ManyToManyField(blank=True, related_name='influencer_who_wrote', to='main.Book'),
        ),
    ]
