# Generated by Django 3.1.7 on 2021-03-14 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210314_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='img_url',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
