# Generated by Django 3.1.7 on 2021-03-14 20:17

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_book_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='influencer',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='media/faustao.jpg', force_format='JPEG', keep_meta=True, null=True, quality=100, size=[1800, 1800], upload_to=''),
        ),
    ]
