# Generated by Django 3.1.7 on 2021-03-17 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210314_2017'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagname', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='influencer',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='influencer_tag', to='main.Tag'),
        ),
    ]
