# Generated by Django 3.1.7 on 2021-03-17 20:32

from django.db import migrations
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210317_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='color',
            field=main.models.ColorField(default='#ffffff', max_length=10),
        ),
    ]
