# Generated by Django 3.1.7 on 2021-03-17 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_tag_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='influencer',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='influencer_tags', to='main.Tag'),
        ),
    ]
