# Generated by Django 3.1.7 on 2021-03-23 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20210323_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='aff_link',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='title_pt',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
